name: Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build wheel
        run: uv build
        working-directory: .

      - name: Store the distribution packages
        uses: actions/upload-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

  publish-to-test-pypi:
    environment:
      name: testpypi
      url: https://test.pypi.org/project/airflow-exporter/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    environment:
      name: pypi
      url: https://pypi.org/project/airflow-exporter/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - build
      - publish-to-test-pypi

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
